# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
    build-app:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
                      - node-v1-{{ .Branch }}-
                      - node-v1-
            - run:
                  name: Bygg React app
                  command: |
                      npm ci
            - save_cache:
                  paths:
                      - ~/usr/local/lib/node_modules
                  key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - run:
                  name: Tester
                  command: |
                      npm run test
            - run:
                  name: Bygg produksjonsversjon av React app
                  command: npm run build

    build-docker:
        docker:
            - image: navikt/deployment-cli:latest
        steps:
            - checkout
            - sett-miljovariabler
            - setup_remote_docker
            - attach_workspace:
                  at: .
            - run:
                  name: Bygger Docker image
                  command: |
                      echo $IMAGE_NAME
                      docker build -t $IMAGE_NAME .
            - run:
                  name: Pusher Docker image
                  command: |
                      echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                      docker push $IMAGE_NAME

    deploy-til-q6:
        docker:
            - image: navikt/deployment-cli:latest
        steps:
            - checkout
            - sett-miljovariabler
            - deploy:
                  cluster: dev-sbs
                  namespace: q6

    deploy-til-q1:
        docker:
            - image: navikt/deployment-cli:latest
        steps:
            - checkout
            - sett-miljovariabler
            - deploy:
                  cluster: dev-sbs
                  namespace: q1

    deploy-til-q0:
        docker:
            - image: navikt/deployment-cli:latest
        steps:
            - checkout
            - sett-miljovariabler
            - deploy:
                  cluster: dev-sbs
                  namespace: q0

    deploy-til-prod:
        docker:
            - image: navikt/deployment-cli:latest
        steps:
            - checkout
            - sett-miljovariabler
            - deploy:
                  cluster: prod-sbs
                  namespace: default

commands:
    deploy:
        parameters:
            cluster:
                type: string
            namespace:
                type: string
        steps:
            - run:
                  name: Deployer til << parameters.cluster >>, namespace << parameters.namespace >>
                  command: |
                      echo $GH_DEPLOY_KEY | base64 -d | dos2unix > gh_deploy_key.pem
                      deployment-cli deploy create \
                          --team=personbruker \
                          --cluster=<< parameters.cluster >> \
                          --resource=.nais/<< parameters.cluster >>-<< parameters.namespace >>.yaml \
                          --repository=$CIRCLE_PROJECT_USERNAME/$REPO_NAME \
                          --var namespace=<< parameters.namespace >> \
                          --var reponame=$REPO_NAME \
                          --var version=$IMAGE_VERSION \
                          --key=gh_deploy_key.pem \
                          --ref=$COMMIT_SHORT \
                          --appid=34043

    sett-miljovariabler:
        steps:
            - run:
                  name: Definerer git-referanse, versjonsnummer og repo-navn
                  command: |
                      echo "export COMMIT_SHORT='$(git rev-parse --short HEAD)'" >> $BASH_ENV
                      echo "export IMAGE_VERSION='$CIRCLE_WORKFLOW_ID-${CIRCLE_BRANCH////-}$CIRCLE_TAG'" >> $BASH_ENV
                      echo "export REPO_NAME='$CIRCLE_PROJECT_REPONAME'" >> $BASH_ENV
            - run:
                  name: Definerer navn på docker-image
                  command: |
                      echo "export IMAGE_NAME='$CIRCLE_PROJECT_USERNAME/$REPO_NAME:$IMAGE_VERSION'" >> $BASH_ENV

workflows:
    bygg-og-deploy:
        jobs:
            - build-app
            - bekreft-deploy-til-dev:
                  type: approval
                  requires:
                      - build-app

            - build-docker:
                  name: build-docker-dev
                  requires:
                      - bekreft-deploy-til-dev

            - deploy-til-q6:
                  requires:
                      - build-docker-dev
            - deploy-til-q1:
                  requires:
                      - build-docker-dev
            - deploy-til-q0:
                  requires:
                      - build-docker-dev

            - bekreft-deploy-til-prod:
                  type: approval
                  requires:
                      - build-app
                  filters:
                      branches:
                          only: master

            - build-docker:
                  name: build-docker-prod
                  requires:
                      - bekreft-deploy-til-prod
                  filters:
                      branches:
                          only: master

            - deploy-til-prod:
                  requires:
                      - build-docker-prod
                  filters:
                      branches:
                          only: master
